:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[resources]]
= Resources

[[resources-auth]]
== Auth

[[resources-auth-login-naver]]
=== 네이버 로그인
operation::auth-naver[snippets='http-request,request-parameters,http-response']

[[resources-auth-login-github]]
=== 깃허브 로그인
operation::auth-github[snippets='http-request,request-parameters,http-response']

[[resources-member]]
== Member

[[resources-member-findMemberOfMine]]
=== 내 회원 정보 조회
operation::member-findMemberOfMine[snippets='http-request,http-response,response-fields']

[[resources-member-update]]
=== 내 회원 정보 한줄 소개 수정
operation::member-updateMemberOfMineIntroduction[snippets='http-request,request-body,request-fields,http-response']

=== 내 회원 정보 제목 수정
operation::member-updateMemberOfMineSubject[snippets='http-request,request-body,request-fields,http-response']

=== 회원 탈퇴
operation::member-delete[snippets='http-request,http-response']

[[resources-post]]
== Post

=== 포스트 작성
operation::post-create[snippets='http-request,request-body,request-fields,http-response']

=== 포스트 조회
operation::post-find[snippets='http-request,path-parameters,http-response,response-fields']

=== 포스트 수정
operation::post-update[snippets='http-request,path-parameters,request-body,request-fields,http-response']

=== 포스트 삭제
operation::post-delete[snippets='http-request,path-parameters,http-response']

=== 포스트 목록 조회
operation::post-findAllPaging[snippets='http-request,request-parameters,http-response,response-fields']

[[resources-comment]]
== Comment

=== 댓글 작성
operation::comment-create[snippets='http-request,path-parameters,request-body,request-fields,http-response,response-fields']

=== 댓글 조회
operation::comment-find[snippets='http-request,path-parameters,http-response,response-fields']

=== 댓글 수정
operation::comment-update[snippets='http-request,path-parameters,request-body,request-fields,http-response']

=== 댓글 삭제
operation::comment-delete[snippets='http-request,path-parameters,http-response']

=== 대댓글 작성
operation::childComment-create[snippets='http-request,path-parameters,request-body,request-fields,http-response,response-fields']